add HTTP 214: Transformation Applied
httpcats/http.cat pull request #216
Opened 2024-03-22 14:16 UTC by karlhiramoto

2024-03-22 16:36 UTC, karlhiramoto commented
If you don't like the image in PR,  Alternative 1:
![image](https://github.com/httpcats/http.cat/assets/22713/4f884658-44ee-4166-bf49-a6417419d07c)

2024-03-25 00:51 UTC, rogeriopvl commented
Hi @karlhiramoto 

Thanks for the contribution! I do actually prefer this last image. Can you update the PR to use this one?

2024-03-25 11:02 UTC, karlhiramoto commented
@rogeriopvl  image updated.

2024-03-27 00:33 UTC, rogeriopvl requested changes

2024-03-27 00:33 UTC, rogeriopvl commented on public/images-original/214.jpg
@karlhiramoto the image is not centered, can you adjust it please?

Thanks

2024-03-27 10:07 UTC, karlhiramoto commented on public/images-original/214.jpg
Done

2024-03-31 15:26 UTC, rogeriopvl commented
@karlhiramoto thanks, merging now. I'll improve the description content in a separate commit.

2024-03-31 15:26 UTC, merged

2024-04-09 07:09 UTC, ddelange commented
this is awesome
[![https://http.cat/202](https://http.cat/202)](https://http.cat/202)